CREATE TABLE urls (
 id SERIAL PRIMARY KEY,
 original_url TEXT NOT NULL,
 short_code TEXT UNIQUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clicks (
 id SERIAL PRIMARY KEY,
 short_code TEXT,
 timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);